In [1]:
!pip install datasets wikipedia-api pandas

Requirement already satisfied: datasets in c:\users\sadly\anaconda3\lib\site-packages (4.8.4)
Requirement already satisfied: wikipedia-api in c:\users\sadly\anaconda3\lib\site-packages (0.13.0)
Requirement already satisfied: pandas in c:\users\sadly\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: filelock in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (3.20.0)
Requirement already satisfied: numpy>=1.17 in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (2.3.5)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: requests>=2.32.2 in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (2.32.5)
Requirement already satisfied: httpx<1.0.0 in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in c:\users\sadly\anaconda3\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.10.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (1.8.0)
Requirement already satisfied: packaging in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\sadly\anaconda3\lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\sadly\anaconda3\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: anyio in c:\users\sadly\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (4.10.0)
Requirement already satisfied: certifi in c:\users\sadly\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\users\sadly\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\sadly\anaconda3\lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\sadly\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in c:\users\sadly\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.2)
Requirement already satisfied: typer in c:\users\sadly\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.20.0)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\sadly\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: click==8.3.1 in c:\users\sadly\anaconda3\lib\site-packages (from wikipedia-api) (8.3.1)
Requirement already satisfied: tenacity==9.1.4 in c:\users\sadly\anaconda3\lib\site-packages (from wikipedia-api) (9.1.4)
Requirement already satisfied: colorama in c:\users\sadly\anaconda3\lib\site-packages (from click==8.3.1->wikipedia-api) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sadly\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sadly\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sadly\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\sadly\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\sadly\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\sadly\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\sadly\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\sadly\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\sadly\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\sadly\anaconda3\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in c:\users\sadly\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sadly\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sadly\anaconda3\lib\site-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\sadly\anaconda3\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\sadly\anaconda3\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\sadly\anaconda3\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\sadly\anaconda3\lib\site-packages (from rich>=10.11.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\sadly\anaconda3\lib\site-packages (from rich>=10.11.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\sadly\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)

In [2]:
import sys
# Устанавливаем библиотеку для готовых датасетов и для работы с Википедией
!{sys.executable} -m pip install datasets Wikipedia-API pandas

Requirement already satisfied: datasets in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (4.8.4)
Requirement already satisfied: Wikipedia-API in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (0.13.0)
Requirement already satisfied: pandas in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (1.5.3)
Requirement already satisfied: filelock in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from datasets) (3.9.1)
Requirement already satisfied: numpy>=1.17 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from datasets) (1.23.5)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: requests>=2.32.2 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from datasets) (2.33.0)
Requirement already satisfied: httpx<1.0.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from datasets) (0.28.1)
Collecting tqdm>=4.66.3 (from datasets)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: xxhash in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.4)
Requirement already satisfied: anyio in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from httpx<1.0.0->datasets) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: click==8.3.1 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from Wikipedia-API) (8.3.1)
Requirement already satisfied: tenacity==9.1.4 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from Wikipedia-API) (9.1.4)
Requirement already satisfied: colorama in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from click==8.3.1->Wikipedia-API) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.64.1
    Uninstalling tqdm-4.64.1:
      Successfully uninstalled tqdm-4.64.1
Successfully installed tqdm-4.67.3

  WARNING: The script tqdm.exe is installed in 'C:\Users\sadly\anaconda3\envs\dp_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
deeppavlov 1.7.0 requires tqdm<4.65.0,>=4.42.0, but you have tqdm 4.67.3 which is incompatible.
spacy 3.8.14 requires pydantic<3.0.0,>=2.0.0, but you have pydantic 1.10.26 which is incompatible.

In [3]:
import sys
# Откатываем pydantic и tqdm к версиям, которые любит DeepPavlov
!{sys.executable} -m pip install "pydantic<2.0" "tqdm<4.65.0"

Requirement already satisfied: pydantic<2.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (1.10.26)
Collecting tqdm<4.65.0
  Using cached tqdm-4.64.1-py2.py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from pydantic<2.0) (4.15.0)
Requirement already satisfied: colorama in c:\users\sadly\anaconda3\envs\dp_env\lib\site-packages (from tqdm<4.65.0) (0.4.6)
Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Installing collected packages: tqdm
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.3
    Uninstalling tqdm-4.67.3:
      Successfully uninstalled tqdm-4.67.3
Successfully installed tqdm-4.64.1

  WARNING: The script tqdm.exe is installed in 'C:\Users\sadly\anaconda3\envs\dp_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 4.8.4 requires tqdm>=4.66.3, but you have tqdm 4.64.1 which is incompatible.
spacy 3.8.14 requires pydantic<3.0.0,>=2.0.0, but you have pydantic 1.10.26 which is incompatible.

In [4]:
import pandas as pd
from datasets import load_dataset

print("Начинаю загрузку SberQuAD из Hugging Face...")

try:
    # Загружаем часть 'train' (обучающая выборка)
    # Выберем только первые 100 записей, чтобы не перегружать память
    dataset = load_dataset("sberquad", split='train[:100]')
    
    # Преобразуем структуру в плоскую таблицу Pandas
    # В SberQuAD ответы лежат в словаре {'text': [...], 'answer_start': [...]}, 
    # мы вытащим только сам текст ответа.
    df_sber = pd.DataFrame({
        'context': dataset['context'],
        'question': dataset['question'],
        'answer': [a['text'][0] for a in dataset['answers']],
        'source': 'SberQuAD'
    })

    print(f"Успешно загружено строк: {len(df_sber)}")
    print("\nПример данных (первые 3 строки):")
    display(df_sber.head(3))

except Exception as e:
    print(f"Произошла ошибка при загрузке: {e}")
    print("Если ошибка 'ModuleNotFoundError', значит нужно еще раз запустить установку pip install datasets")

C:\Users\sadly\anaconda3\envs\dp_env\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Начинаю загрузку SberQuAD из Hugging Face...
Успешно загружено строк: 100

Пример данных (первые 3 строки):

,context,question,answer,source
0,В протерозойских отложениях органические остат...,чем представлены органические остатки?,известковыми выделениями сине-зелёных водорослей,SberQuAD
1,В протерозойских отложениях органические остат...,что найдено в кремнистых сланцах железорудной ...,"нитевидные водоросли, грибные нити",SberQuAD
2,В протерозойских отложениях органические остат...,что встречается в протерозойских отложениях?,органические остатки,SberQuAD

In [5]:
import pandas as pd
from datasets import load_dataset
import os

print("Начинаю загрузку ПОЛНОГО датасета SberQuAD")

try:
    # Загружаем весь обучающий набор (train)
    full_dataset = load_dataset("sberquad", split='train')
    
    # Преобразуем в DataFrame
    # Извлекаем текст ответа из вложенного словаря
    df_full_sber = pd.DataFrame({
        'context': full_dataset['context'],
        'question': full_dataset['question'],
        'answer': [a['text'][0] for a in full_dataset['answers']],
        'source': 'SberQuAD_Full'
    })

    print(f"Загрузка завершена! Всего строк: {len(df_full_sber)}")

    # СОХРАНЕНИЕ В ФАЙЛ
    file_path = 'sberquad_full_dataset.csv'
    df_full_sber.to_csv(file_path, index=False, encoding='utf-8')
    
    print(f"\nФайл '{file_path}' успешно создан в твоей папке!")
    print(f"Размер файла на диске: ~{os.path.getsize(file_path) / (1024*1024):.2f} MB")

    # Посмотрим на случайные 5 строк из середины
    display(df_full_sber.sample(5))

except Exception as e:
    print(f"Произошла ошибка: {e}")

Начинаю загрузку ПОЛНОГО датасета SberQuAD
Загрузка завершена! Всего строк: 45328

Файл 'sberquad_full_dataset.csv' успешно создан в твоей папке!
Размер файла на диске: ~67.25 MB

,context,question,answer,source
31720,Сопоставление текущей доходности облигаций и б...,Что подразумевается под фиксированной суммой в...,оставшиеся до погашения проценты и в конце сро...,SberQuAD_Full
44365,"В учебной литературе по финансам, издаваемой п...",Где продолжают излагаться основные теоретическ...,"В учебной литературе по финансам, издаваемой п...",SberQuAD_Full
4958,Все крупные спутники Юпитера вращаются синхрон...,Какова плотность Европы?,"2,99 г/см³",SberQuAD_Full
8120,В начале XX века английский бактериолог Фредер...,Кто определил число вирусных частиц в первонач...,Феликс Д’Эрелль,SberQuAD_Full
31222,Идея организации такого забега была предложена...,Когда женский марафон был впервые введён в про...,в 1984 году,SberQuAD_Full

In [10]:
from datasets import load_dataset
import pandas as pd

print("Загружаю датасет MuSeRC (второй источник с вопросами и вариантами ответов)...")

try:
    # Загружаем MuSeRC из коллекции Russian SuperGLUE
    # Берем тренировочную часть
    muserc = load_dataset("russian_superglue", "muserc", split='train')

    muserc_data = []

    # Проходим по данным. В MuSeRC структура сложнее: 
    # Текст -> Список вопросов -> Список ответов (True/False)
    for example in muserc:
        context = example['paragraph']
        question = example['question']
        
        # Находим правильный ответ среди вариантов
        # В этом датасете 'answer' - это текст варианта, а 'label' (1 или 0) - верный он или нет
        correct_answer = ""
        all_options = []
        
        # В MuSeRC ответы привязаны к вопросам. Мы упростим структуру для датасета.
        # Для твоей курсовой это золото, т.к. тут есть и правильные, и неправильные варианты!
        answer_text = example['answer']
        is_correct = example['label']
        
        muserc_data.append({
            'context': context,
            'question': question,
            'answer': answer_text,
            'is_correct': is_correct, # 1 если верный, 0 если дистрактор (неверный)
            'source': 'MuSeRC'
        })

    # Создаем таблицу
    df_muserc = pd.DataFrame(muserc_data)
    
    # Чтобы не путаться, давай оставим только ПРАВИЛЬНЫЕ ответы (как в SberQuAD)
    # Но для курсовой ты потом сможешь вытащить и неверные!
    df_muserc_correct = df_muserc[df_muserc['is_correct'] == 1].head(10000)

    print(f"Успех! Собрано {len(df_muserc_correct)} пар вопрос-ответ из MuSeRC.")

    # СОХРАНЕНИЕ ВО ВТОРОЙ ФАЙЛ
    file_name = 'muserc_qa_dataset.csv'
    df_muserc_correct.to_csv(file_name, index=False, encoding='utf-8-sig')

    print(f"Файл '{file_name}' успешно создан.")
    display(df_muserc_correct.head(3))

except Exception as e:
    print(f"Ошибка при загрузке MuSeRC: {e}")

Загружаю датасет MuSeRC (второй источник с вопросами и вариантами ответов)...
Ошибка при загрузке MuSeRC: Dataset 'russian_superglue' doesn't exist on the Hub or cannot be accessed.

In [13]:
import pandas as pd
from datasets import load_dataset
import os

print("Начинаю загрузку ПРОВЕРОЧНОГО датасета SberQuAD (Validation split)...")

try:
    # Загружаем проверочную часть (она содержит около 5 000 строк)
    val_dataset = load_dataset("sberquad", split='validation')
    
    # Преобразуем в таблицу
    df_val_sber = pd.DataFrame({
        'context': val_dataset['context'],
        'question': val_dataset['question'],
        'answer': [a['text'][0] for a in val_dataset['answers']],
        'source': 'SberQuAD_Validation'
    })

    print(f"Загрузка завершена! Всего строк: {len(df_val_sber)}")

    # СОХРАНЕНИЕ ВО ВТОРОЙ ФАЙЛ
    file_path_val = 'sberquad_val_dataset.csv'
    df_val_sber.to_csv(file_path_val, index=False, encoding='utf-8-sig')
    
    print(f"\nФайл '{file_path_val}' успешно создан в твоей папке!")
    print(f"Размер файла: ~{os.path.getsize(file_path_val) / (1024*1024):.2f} MB")

    # Посмотрим на первые 5 строк
    display(df_val_sber.head(5))

except Exception as e:
    print(f"Произошла ошибка: {e}")

Начинаю загрузку ПРОВЕРОЧНОГО датасета SberQuAD (Validation split)...
Загрузка завершена! Всего строк: 5036

Файл 'sberquad_val_dataset.csv' успешно создан в твоей папке!
Размер файла: ~7.51 MB

,context,question,answer,source
0,Первые упоминания о строении человеческого тел...,Где встречаются первые упоминания о строении ч...,в Древнем Египте,SberQuAD_Validation
1,Первые упоминания о строении человеческого тел...,Когда египетский врач Имхотеп впервые описал н...,В XXVII веке до н. э.,SberQuAD_Validation
2,Телескоп имеет модульную структуру и содержит ...,Как называется корректирующая оптическая систе...,COSTAR,SberQuAD_Validation
3,Критики теории Вегенера поставили во главу угл...,Какая теория была отвергнута после смерти Веге...,теория дрейфа материков,SberQuAD_Validation
4,При нагревании кусочки янтаря становятся очень...,Чему не уступают по красоте изделия из прессов...,изделиям из монолитных камней,SberQuAD_Validation